"""
Uploads API.

Routes:
POST /uploads/avatar
POST /uploads/voice
POST /uploads/image
POST /uploads/video

GET  /uploads/avatars/{filename}
GET  /uploads/voice/{filename}
GET  /uploads/images/{filename}
GET  /uploads/videos/{filename}

Production notes:
- Avatar upload is available for authenticated users.
- Voice/image/video upload is protected by subscription:
  - coach must have active subscription;
  - client must belong to a coach with active subscription.
- Avatar and chat images are re-encoded to JPEG.
- Video files are validated and stored as-is.
- File names are generated by the backend only.
- Supports local storage and S3-compatible cloud storage such as Cloudflare R2.
"""

import logging
import os
import re
import uuid
from io import BytesIO
from pathlib import Path

from fastapi import APIRouter, Depends, File, HTTPException, UploadFile, status
from fastapi.responses import FileResponse
from PIL import Image, ImageOps, UnidentifiedImageError
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.core.deps import (
    get_current_user,
    require_active_client_coach_subscription,
    require_active_coach_subscription,
)
from app.db.database import get_db
from app.models.user import User
from app.services.storage_service import get_storage_service


logger = logging.getLogger(__name__)
settings = get_settings()

router = APIRouter(prefix="/uploads", tags=["Uploads"])


BASE_DIR = Path(__file__).resolve().parents[2]
UPLOAD_DIR = BASE_DIR / "uploads"

AVATAR_DIR = UPLOAD_DIR / "avatars"
VOICE_DIR = UPLOAD_DIR / "voice"
IMAGE_DIR = UPLOAD_DIR / "images"
VIDEO_DIR = UPLOAD_DIR / "videos"

MAX_IMAGE_SIZE = 10 * 1024 * 1024
MAX_AUDIO_SIZE = 15 * 1024 * 1024
MAX_VIDEO_SIZE = 120 * 1024 * 1024

AVATAR_THUMBNAIL_SIZE = (900, 900)
CHAT_IMAGE_MAX_SIZE = (1600, 1600)

IMAGE_JPEG_QUALITY = 86
CHAT_IMAGE_JPEG_QUALITY = 88

Image.MAX_IMAGE_PIXELS = 16_000_000

ALLOWED_IMAGE_TYPES = {
    "image/jpeg",
    "image/jpg",
    "image/png",
    "image/webp",
    "application/octet-stream",
}

ALLOWED_AUDIO_TYPES = {
    "audio/m4a": ".m4a",
    "audio/x-m4a": ".m4a",
    "audio/mp4": ".m4a",
    "audio/mpeg": ".mp3",
    "audio/mp3": ".mp3",
    "audio/wav": ".wav",
    "audio/x-wav": ".wav",
    "audio/aac": ".aac",
    "audio/x-aac": ".aac",
    "audio/webm": ".webm",
    "application/octet-stream": ".m4a",
}

ALLOWED_VIDEO_TYPES = {
    "video/mp4": ".mp4",
    "video/quicktime": ".mov",
    "video/mov": ".mov",
    "video/webm": ".webm",
    "application/octet-stream": ".mp4",
}

VOICE_MEDIA_TYPES = {
    ".m4a": "audio/mp4",
    ".mp3": "audio/mpeg",
    ".wav": "audio/wav",
    ".aac": "audio/aac",
    ".webm": "audio/webm",
}

VIDEO_MEDIA_TYPES = {
    ".mp4": "video/mp4",
    ".mov": "video/quicktime",
    ".webm": "video/webm",
}

SAFE_FILENAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def ensure_upload_dirs() -> None:
    AVATAR_DIR.mkdir(parents=True, exist_ok=True)
    VOICE_DIR.mkdir(parents=True, exist_ok=True)
    IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    VIDEO_DIR.mkdir(parents=True, exist_ok=True)


def build_public_url(path: str) -> str:
    """
    Returns absolute URL if APP_PUBLIC_URL is configured,
    otherwise returns relative API path.
    """

    normalized_path = path if path.startswith("/") else f"/{path}"

    if not settings.APP_PUBLIC_URL:
        return normalized_path

    return f"{settings.APP_PUBLIC_URL.rstrip('/')}{normalized_path}"


def validate_safe_filename(filename: str) -> str:
    safe_name = os.path.basename(filename).strip()

    if not safe_name:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid filename",
        )

    if safe_name != filename:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid filename",
        )

    if not SAFE_FILENAME_RE.fullmatch(safe_name):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid filename",
        )

    return safe_name


def get_storage_prefix(name: str, fallback: str) -> str:
    value = getattr(settings, name, None)

    if isinstance(value, str) and value.strip():
        return value.strip("/")

    return fallback.strip("/")


async def read_upload_with_limit(
    file: UploadFile,
    max_size: int,
) -> bytes:
    """
    Reads UploadFile safely with max size limit.
    """

    chunks: list[bytes] = []
    total_size = 0

    while True:
        chunk = await file.read(1024 * 1024)

        if not chunk:
            break

        total_size += len(chunk)

        if total_size > max_size:
            raise HTTPException(
                status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                detail=f"File is too large. Max size is {max_size // (1024 * 1024)} MB",
            )

        chunks.append(chunk)

    return b"".join(chunks)


async def ensure_media_upload_allowed(
    current_user: User,
    db: AsyncSession,
) -> None:
    """
    Voice/image/video messages are subscription-protected features.

    - Coach: must have active coach subscription.
    - Client: assigned coach must have active subscription.
    """

    if current_user.role == "coach":
        await require_active_coach_subscription(current_user, db)
        return

    if current_user.role == "client":
        await require_active_client_coach_subscription(current_user, db)
        return

    raise HTTPException(
        status_code=status.HTTP_403_FORBIDDEN,
        detail="Unsupported user role",
    )


def prepare_jpeg_image(
    *,
    content: bytes,
    filename_prefix: str,
    max_size: tuple[int, int],
    quality: int,
) -> tuple[str, bytes]:
    """
    Validates uploaded image and converts it to optimized JPEG bytes.
    """

    try:
        image = Image.open(BytesIO(content))
        image.verify()

        image = Image.open(BytesIO(content))
        image = ImageOps.exif_transpose(image)
        image = image.convert("RGB")
        image.thumbnail(max_size)

        output = BytesIO()

        image.save(
            output,
            format="JPEG",
            quality=quality,
            optimize=True,
            progressive=True,
        )

        filename = f"{filename_prefix}_{uuid.uuid4().hex[:16]}.jpg"

        return filename, output.getvalue()

    except UnidentifiedImageError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid image file",
        ) from exc

    except Exception as exc:
        logger.exception("Image processing failed")

        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Could not process image. Please choose another file.",
        ) from exc


def save_local_file(
    *,
    directory: Path,
    filename: str,
    content: bytes,
) -> Path:
    filepath = directory / filename

    try:
        directory.mkdir(parents=True, exist_ok=True)

        with open(filepath, "wb") as output:
            output.write(content)

        return filepath

    except Exception as exc:
        logger.exception("File saving failed")

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not save uploaded file",
        ) from exc


def upload_bytes_to_storage_or_local(
    *,
    content: bytes,
    filename: str,
    content_type: str,
    cloud_prefix: str,
    local_dir: Path,
    local_api_path: str,
    cache_control: str,
) -> tuple[str, str]:
    """
    Uploads file either to local disk or cloud storage.

    Returns:
    - stored_url: value that should be saved/used by frontend
    - public_url: absolute public URL when available
    """

    if settings.uses_cloud_storage:
        storage = get_storage_service()
        key = f"{cloud_prefix.strip('/')}/{filename}"

        try:
            result = storage.upload_bytes(
                content=content,
                key=key,
                content_type=content_type,
                cache_control=cache_control,
            )

        except RuntimeError as exc:
            logger.exception("Cloud upload failed")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Could not upload file to cloud storage",
            ) from exc

        return result.public_url, result.public_url

    ensure_upload_dirs()

    save_local_file(
        directory=local_dir,
        filename=filename,
        content=content,
    )

    relative_url = f"{local_api_path.rstrip('/')}/{filename}"
    public_url = build_public_url(relative_url)

    return relative_url, public_url


@router.post("/avatar")
async def upload_avatar(
    file: UploadFile = File(...),
    current_user: User = Depends(get_current_user),
):
    content_type = file.content_type or "application/octet-stream"

    if content_type not in ALLOWED_IMAGE_TYPES:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=f"Unsupported image type: {content_type}",
        )

    try:
        content = await read_upload_with_limit(
            file=file,
            max_size=MAX_IMAGE_SIZE,
        )

        filename, jpeg_content = prepare_jpeg_image(
            content=content,
            filename_prefix=current_user.id,
            max_size=AVATAR_THUMBNAIL_SIZE,
            quality=IMAGE_JPEG_QUALITY,
        )

        avatar_url, public_url = upload_bytes_to_storage_or_local(
            content=jpeg_content,
            filename=filename,
            content_type="image/jpeg",
            cloud_prefix=get_storage_prefix("STORAGE_AVATAR_PREFIX", "avatars"),
            local_dir=AVATAR_DIR,
            local_api_path="/api/v1/uploads/avatars",
            cache_control="public, max-age=31536000, immutable",
        )

    finally:
        await file.close()

    return {
        "avatarUrl": avatar_url,
        "avatar_url": avatar_url,
        "publicUrl": public_url,
        "public_url": public_url,
        "filename": filename,
        "storage": settings.STORAGE_PROVIDER,
    }


@router.post("/voice")
async def upload_voice(
    file: UploadFile = File(...),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    await ensure_media_upload_allowed(
        current_user=current_user,
        db=db,
    )

    content_type = file.content_type or "application/octet-stream"

    if content_type not in ALLOWED_AUDIO_TYPES:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=f"Unsupported audio type: {content_type}",
        )

    try:
        content = await read_upload_with_limit(
            file=file,
            max_size=MAX_AUDIO_SIZE,
        )

        extension = ALLOWED_AUDIO_TYPES[content_type]
        filename = f"{current_user.id}_{uuid.uuid4().hex[:16]}{extension}"
        response_content_type = VOICE_MEDIA_TYPES.get(extension, content_type)

        voice_url, public_url = upload_bytes_to_storage_or_local(
            content=content,
            filename=filename,
            content_type=response_content_type,
            cloud_prefix=get_storage_prefix("STORAGE_VOICE_PREFIX", "voice"),
            local_dir=VOICE_DIR,
            local_api_path="/api/v1/uploads/voice",
            cache_control="public, max-age=86400",
        )

    finally:
        await file.close()

    return {
        "voiceUrl": voice_url,
        "voice_url": voice_url,
        "publicUrl": public_url,
        "public_url": public_url,
        "filename": filename,
        "storage": settings.STORAGE_PROVIDER,
    }


@router.post("/image")
async def upload_chat_image(
    file: UploadFile = File(...),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    await ensure_media_upload_allowed(
        current_user=current_user,
        db=db,
    )

    content_type = file.content_type or "application/octet-stream"

    if content_type not in ALLOWED_IMAGE_TYPES:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=f"Unsupported image type: {content_type}",
        )

    try:
        content = await read_upload_with_limit(
            file=file,
            max_size=MAX_IMAGE_SIZE,
        )

        filename, jpeg_content = prepare_jpeg_image(
            content=content,
            filename_prefix=current_user.id,
            max_size=CHAT_IMAGE_MAX_SIZE,
            quality=CHAT_IMAGE_JPEG_QUALITY,
        )

        image_url, public_url = upload_bytes_to_storage_or_local(
            content=jpeg_content,
            filename=filename,
            content_type="image/jpeg",
            cloud_prefix=get_storage_prefix("STORAGE_IMAGE_PREFIX", "images"),
            local_dir=IMAGE_DIR,
            local_api_path="/api/v1/uploads/images",
            cache_control="public, max-age=31536000, immutable",
        )

    finally:
        await file.close()

    return {
        "mediaUrl": image_url,
        "media_url": image_url,
        "imageUrl": image_url,
        "image_url": image_url,
        "mediaType": "image",
        "media_type": "image",
        "publicUrl": public_url,
        "public_url": public_url,
        "filename": filename,
        "storage": settings.STORAGE_PROVIDER,
    }


@router.post("/video")
async def upload_chat_video(
    file: UploadFile = File(...),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    await ensure_media_upload_allowed(
        current_user=current_user,
        db=db,
    )

    content_type = file.content_type or "application/octet-stream"

    if content_type not in ALLOWED_VIDEO_TYPES:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=f"Unsupported video type: {content_type}",
        )

    try:
        content = await read_upload_with_limit(
            file=file,
            max_size=MAX_VIDEO_SIZE,
        )

        extension = ALLOWED_VIDEO_TYPES[content_type]
        filename = f"{current_user.id}_{uuid.uuid4().hex[:16]}{extension}"
        response_content_type = VIDEO_MEDIA_TYPES.get(extension, content_type)

        video_url, public_url = upload_bytes_to_storage_or_local(
            content=content,
            filename=filename,
            content_type=response_content_type,
            cloud_prefix=get_storage_prefix("STORAGE_VIDEO_PREFIX", "videos"),
            local_dir=VIDEO_DIR,
            local_api_path="/api/v1/uploads/videos",
            cache_control="public, max-age=604800",
        )

    finally:
        await file.close()

    return {
        "mediaUrl": video_url,
        "media_url": video_url,
        "videoUrl": video_url,
        "video_url": video_url,
        "mediaType": "video",
        "media_type": "video",
        "publicUrl": public_url,
        "public_url": public_url,
        "filename": filename,
        "storage": settings.STORAGE_PROVIDER,
    }


@router.get("/avatars/{filename}")
async def get_avatar(filename: str):
    """
    Serves locally stored avatars.

    In cloud storage mode, newly uploaded avatars are served directly
    by the storage public URL/CDN, but this route remains for old local files.
    """

    ensure_upload_dirs()

    safe_name = validate_safe_filename(filename)
    filepath = AVATAR_DIR / safe_name

    if not filepath.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Avatar not found",
        )

    return FileResponse(
        filepath,
        media_type="image/jpeg",
        headers={
            "Cache-Control": "public, max-age=31536000, immutable",
            "X-Content-Type-Options": "nosniff",
        },
    )


@router.get("/voice/{filename}")
async def get_voice(filename: str):
    """
    Serves locally stored voice files.

    In cloud storage mode, newly uploaded voice files are served directly
    by the storage public URL/CDN, but this route remains for old local files.
    """

    ensure_upload_dirs()

    safe_name = validate_safe_filename(filename)
    filepath = VOICE_DIR / safe_name

    if not filepath.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Voice file not found",
        )

    extension = filepath.suffix.lower()
    media_type = VOICE_MEDIA_TYPES.get(extension, "application/octet-stream")

    return FileResponse(
        filepath,
        media_type=media_type,
        headers={
            "Accept-Ranges": "bytes",
            "Cache-Control": "public, max-age=86400",
            "X-Content-Type-Options": "nosniff",
        },
    )


@router.get("/images/{filename}")
async def get_chat_image(filename: str):
    """
    Serves locally stored chat images.

    In cloud storage mode, newly uploaded images are served directly
    by the storage public URL/CDN, but this route remains for old local files.
    """

    ensure_upload_dirs()

    safe_name = validate_safe_filename(filename)
    filepath = IMAGE_DIR / safe_name

    if not filepath.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Image file not found",
        )

    return FileResponse(
        filepath,
        media_type="image/jpeg",
        headers={
            "Cache-Control": "public, max-age=31536000, immutable",
            "X-Content-Type-Options": "nosniff",
        },
    )


@router.get("/videos/{filename}")
async def get_chat_video(filename: str):
    """
    Serves locally stored chat videos.

    In cloud storage mode, newly uploaded videos are served directly
    by the storage public URL/CDN, but this route remains for old local files.
    """

    ensure_upload_dirs()

    safe_name = validate_safe_filename(filename)
    filepath = VIDEO_DIR / safe_name

    if not filepath.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Video file not found",
        )

    extension = filepath.suffix.lower()
    media_type = VIDEO_MEDIA_TYPES.get(extension, "application/octet-stream")

    return FileResponse(
        filepath,
        media_type=media_type,
        headers={
            "Accept-Ranges": "bytes",
            "Cache-Control": "public, max-age=604800",
            "X-Content-Type-Options": "nosniff",
        },
    )