"""
Uploads API.

Routes:
POST /uploads/avatar
POST /uploads/voice

GET  /uploads/avatars/{filename}
GET  /uploads/voice/{filename}

Production notes:
- Avatar upload is available for authenticated users.
- Voice upload is protected by subscription:
  - coach must have active subscription;
  - client must belong to a coach with active subscription.
- Uploaded images are re-encoded to JPEG.
- File names are generated by the backend only.
"""

import logging
import os
import re
import uuid
from io import BytesIO
from pathlib import Path

from fastapi import APIRouter, Depends, File, HTTPException, UploadFile, status
from fastapi.responses import FileResponse
from PIL import Image, ImageOps, UnidentifiedImageError
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.core.deps import (
    get_current_user,
    require_active_client_coach_subscription,
    require_active_coach_subscription,
)
from app.db.database import get_db
from app.models.user import User


logger = logging.getLogger(__name__)
settings = get_settings()

router = APIRouter(prefix="/uploads", tags=["Uploads"])


BASE_DIR = Path(__file__).resolve().parents[2]
UPLOAD_DIR = BASE_DIR / "uploads"
AVATAR_DIR = UPLOAD_DIR / "avatars"
VOICE_DIR = UPLOAD_DIR / "voice"

MAX_IMAGE_SIZE = 8 * 1024 * 1024
MAX_AUDIO_SIZE = 15 * 1024 * 1024

IMAGE_THUMBNAIL_SIZE = (900, 900)
IMAGE_JPEG_QUALITY = 86

Image.MAX_IMAGE_PIXELS = 12_000_000

ALLOWED_IMAGE_TYPES = {
    "image/jpeg",
    "image/jpg",
    "image/png",
    "image/webp",
    "application/octet-stream",
}

ALLOWED_AUDIO_TYPES = {
    "audio/m4a": ".m4a",
    "audio/x-m4a": ".m4a",
    "audio/mp4": ".m4a",
    "audio/mpeg": ".mp3",
    "audio/mp3": ".mp3",
    "audio/wav": ".wav",
    "audio/x-wav": ".wav",
    "audio/aac": ".aac",
    "audio/x-aac": ".aac",
    "audio/webm": ".webm",
    "application/octet-stream": ".m4a",
}

VOICE_MEDIA_TYPES = {
    ".m4a": "audio/mp4",
    ".mp3": "audio/mpeg",
    ".wav": "audio/wav",
    ".aac": "audio/aac",
    ".webm": "audio/webm",
}

SAFE_FILENAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def ensure_upload_dirs() -> None:
    AVATAR_DIR.mkdir(parents=True, exist_ok=True)
    VOICE_DIR.mkdir(parents=True, exist_ok=True)


def build_public_url(path: str) -> str:
    """
    Returns absolute URL if APP_PUBLIC_URL is configured,
    otherwise returns relative API path.
    """

    normalized_path = path if path.startswith("/") else f"/{path}"

    if not settings.APP_PUBLIC_URL:
        return normalized_path

    return f"{settings.APP_PUBLIC_URL.rstrip('/')}{normalized_path}"


def validate_safe_filename(filename: str) -> str:
    safe_name = os.path.basename(filename).strip()

    if not safe_name:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid filename",
        )

    if safe_name != filename:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid filename",
        )

    if not SAFE_FILENAME_RE.fullmatch(safe_name):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid filename",
        )

    return safe_name


async def read_upload_with_limit(
    file: UploadFile,
    max_size: int,
) -> bytes:
    """
    Reads UploadFile safely with max size limit.
    """

    chunks: list[bytes] = []
    total_size = 0

    while True:
        chunk = await file.read(1024 * 1024)

        if not chunk:
            break

        total_size += len(chunk)

        if total_size > max_size:
            raise HTTPException(
                status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                detail=f"File is too large. Max size is {max_size // (1024 * 1024)} MB",
            )

        chunks.append(chunk)

    return b"".join(chunks)


async def ensure_voice_upload_allowed(
    current_user: User,
    db: AsyncSession,
) -> None:
    """
    Voice messages are a subscription-protected feature.

    - Coach: must have active coach subscription.
    - Client: assigned coach must have active subscription.
    """

    if current_user.role == "coach":
        await require_active_coach_subscription(current_user, db)
        return

    if current_user.role == "client":
        await require_active_client_coach_subscription(current_user, db)
        return

    raise HTTPException(
        status_code=status.HTTP_403_FORBIDDEN,
        detail="Unsupported user role",
    )


def save_avatar_image(
    *,
    content: bytes,
    user_id: str,
) -> tuple[str, Path]:
    """
    Validates and converts uploaded image to JPEG.
    """

    try:
        image = Image.open(BytesIO(content))
        image.verify()

        image = Image.open(BytesIO(content))
        image = ImageOps.exif_transpose(image)
        image = image.convert("RGB")
        image.thumbnail(IMAGE_THUMBNAIL_SIZE)

        filename = f"{user_id}_{uuid.uuid4().hex[:16]}.jpg"
        filepath = AVATAR_DIR / filename

        image.save(
            filepath,
            format="JPEG",
            quality=IMAGE_JPEG_QUALITY,
            optimize=True,
            progressive=True,
        )

        return filename, filepath

    except UnidentifiedImageError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid image file",
        ) from exc

    except Exception as exc:
        logger.exception("Avatar image processing failed")

        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Could not process image. Please choose another photo.",
        ) from exc


def save_voice_file(
    *,
    content: bytes,
    user_id: str,
    extension: str,
) -> tuple[str, Path]:
    filename = f"{user_id}_{uuid.uuid4().hex[:16]}{extension}"
    filepath = VOICE_DIR / filename

    try:
        with open(filepath, "wb") as output:
            output.write(content)

        return filename, filepath

    except Exception as exc:
        logger.exception("Voice file saving failed")

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not save voice file",
        ) from exc


@router.post("/avatar")
async def upload_avatar(
    file: UploadFile = File(...),
    current_user: User = Depends(get_current_user),
):
    ensure_upload_dirs()

    content_type = file.content_type or "application/octet-stream"

    if content_type not in ALLOWED_IMAGE_TYPES:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=f"Unsupported image type: {content_type}",
        )

    try:
        content = await read_upload_with_limit(
            file=file,
            max_size=MAX_IMAGE_SIZE,
        )

        filename, _ = save_avatar_image(
            content=content,
            user_id=current_user.id,
        )

    finally:
        await file.close()

    relative_url = f"/api/v1/uploads/avatars/{filename}"
    public_url = build_public_url(relative_url)

    return {
        "avatarUrl": relative_url,
        "avatar_url": relative_url,
        "publicUrl": public_url,
        "public_url": public_url,
        "filename": filename,
    }


@router.post("/voice")
async def upload_voice(
    file: UploadFile = File(...),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    await ensure_voice_upload_allowed(
        current_user=current_user,
        db=db,
    )

    ensure_upload_dirs()

    content_type = file.content_type or "application/octet-stream"

    if content_type not in ALLOWED_AUDIO_TYPES:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=f"Unsupported audio type: {content_type}",
        )

    try:
        content = await read_upload_with_limit(
            file=file,
            max_size=MAX_AUDIO_SIZE,
        )

        extension = ALLOWED_AUDIO_TYPES[content_type]

        filename, _ = save_voice_file(
            content=content,
            user_id=current_user.id,
            extension=extension,
        )

    finally:
        await file.close()

    relative_url = f"/api/v1/uploads/voice/{filename}"
    public_url = build_public_url(relative_url)

    return {
        "voiceUrl": relative_url,
        "voice_url": relative_url,
        "publicUrl": public_url,
        "public_url": public_url,
        "filename": filename,
    }


@router.get("/avatars/{filename}")
async def get_avatar(filename: str):
    ensure_upload_dirs()

    safe_name = validate_safe_filename(filename)
    filepath = AVATAR_DIR / safe_name

    if not filepath.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Avatar not found",
        )

    return FileResponse(
        filepath,
        media_type="image/jpeg",
        headers={
            "Cache-Control": "public, max-age=31536000, immutable",
            "X-Content-Type-Options": "nosniff",
        },
    )


@router.get("/voice/{filename}")
async def get_voice(filename: str):
    ensure_upload_dirs()

    safe_name = validate_safe_filename(filename)
    filepath = VOICE_DIR / safe_name

    if not filepath.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Voice file not found",
        )

    extension = filepath.suffix.lower()
    media_type = VOICE_MEDIA_TYPES.get(extension, "application/octet-stream")

    return FileResponse(
        filepath,
        media_type=media_type,
        headers={
            "Accept-Ranges": "bytes",
            "Cache-Control": "private, max-age=86400",
            "X-Content-Type-Options": "nosniff",
        },
    )